114 add condo units with negative predicted values to declared livablenon livable spaces tables
ccao-data/data-architecture pull request #116
Opened 2023-09-05 15:18 UTC by wrridgeway

@carolinedavidson discovered some condo units with negative predicted values in her condo report. We believe these units are likely non-livable and should be treated as such during modeling, reporting, etc.

This PR adds this data to ingest scripts (`ccao-condominium_parking.R`), generates an Athena table for the data, and adds it to the Athena condo characteristics view (`default.vw_pin_condo_char`).

2023-09-05 16:16 UTC, wrridgeway commented
@wagnerlmichael once this PR is merged, we'll need to change your sql syntax where it interacts with `is_question_garage_unit`. It will work how you initially assumed it should (i.e. `NULL` values will become `FALSE`).

2023-09-11 15:13 UTC, dfsnow requested changes

2023-09-11 15:13 UTC, dfsnow commented on aws-athena/views/default-vw_pin_condo_char.sql
> +-- Some condo PINs have been detected as non-livable through modeling
**suggestion:** Can we add a little more context here i.e:

```suggestion
-- In the process of QC'ing condo data, we discovered that some condo units
-- received (unused) negative predicted values. These units were non-livable units
-- incorrectly classified as livable. They received negative predicted values due to 
-- their very low % of ownership. This CTE excludes them from the model going forward.
```

2023-09-11 15:13 UTC, dfsnow commented on aws-s3/scripts-ccao-data-raw-us-east-1/ccao-condominium_parking.R
> +  "O:/Condo Worksheets/Condo 2022/2022 Desk Review - Questionable Garage Units.xlsx", # styler: off
**suggestion:** We really shouldn't be ingesting much from the network drives. Can we move these files to the raw data S3 bucket?

2023-09-13 14:41 UTC, wrridgeway commented on aws-athena/views/default-vw_pin_condo_char.sql
> +            OR negative_preds.is_negative_pred = TRUE
personally, i think `= TRUE ` is more explicit and doesn't detract from anything?

2023-09-13 16:01 UTC, dfsnow requested changes
@wrridgeway Let's generalize this change a bit more to cover any future flags of non-livable condo units uncovered by the Data Dept. I would call the table something like `pin_non_livable_flags_data_team` or similar. Add an extra column that includes the reason for the flag (in this case, negative predicted values).

2023-09-13 21:53 UTC, wrridgeway commented
@jeancochrane I'm kind of at a loss here as to why DBT has started throwing an error that it wasn't throwing before... any clue what I'm doing wrong?

2023-09-13 21:59 UTC, jeancochrane commented
@wrridgeway Hmm, that's weird; seems like something may be off with the deferral to the production state. I'll investigate, but in the meantime you should be able to fix it by clearing the cache (i.e. deleting the object `s3://ccao-dbt-cache-us-east-1/pr-caches/114-add-condo-units-with-negative-predicted-values-to-declared-livablenon-livable-spaces-tables/manifest.json` in S3) and rerunning the build.

2023-09-14 13:57 UTC, wrridgeway commented
Thanks @jeancochrane worked like a charm!

2023-09-14 14:56 UTC, wrridgeway commented
Once this is merged, we'll need to delete `ccao.pin_399_garage_units`, `ccao.pin_negative_predicted_value`, and `ccao.pin_questionable_garage_units` from s3/athena

2023-09-14 15:06 UTC, dfsnow approved these changes

2023-09-14 15:07 UTC, merged