Tweak Res Edit town close QC report to store percentage columns as numbers
ccao-data/data-architecture pull request #606
Opened 2024-09-18 19:13 UTC by jeancochrane

Tia and Tom called me this morning to report that column sorting for the percentage columns in the `Res Edit` town close report wasn't behaving as they expected. It turns out that we're casting those values to strings, which causes Excel to sort them as strings instead of numbers.

This PR adds a new `number_format` option to the `export_format` config blocks that we use to format columns in the QC reports. It uses `number_format` to format the `Res Edit` percent columns as percentages, which causes sort behavior to work as expected.

2024-09-18 19:20 UTC, jeancochrane commented on dbt/scripts/utils/export.py
> +                column_format_by_index = {}
The refactor in this file is more substantial than I was expecting, and we could probably have gotten away with a smaller change, but my motivation was to reduce the number of times we iterate the rows of the spreadsheet to apply formatting. By parsing the column formats ahead of time, we can apply them all in one pass, in contrast to the previous approach that required a separate pass for each format config.

2024-09-18 19:20 UTC, jeancochrane commented on dbt/scripts/utils/export.py
> -                                row[idx].alignment = horizontal_alignment
In contrast to the `parid` formatting above, the previous version of this loop wouldn't have handled single-row spreadsheets properly (i.e. empty sheets with only a header row). We hadn't yet run into a case where this loop needed to format an empty sheet, so it hadn't caused problems yet, but the refactor will handle this case much better if it ever comes up.

2024-09-18 20:25 UTC, dfsnow requested changes
@jeancochrane The code here looks good, however, the column formatting for `Res edit.xlsx` still seems wrong. It looks like the number formatting _is_ applied (per the Number dropdown in the Home menu), but the percentage number is still stored as text.

2024-09-19 19:36 UTC, dfsnow approved these changes

2024-09-19 19:58 UTC, merged