Investigate idot data
ccao-data/data-architecture pull request #617
Opened 2024-10-07 16:59 UTC by Damonamajor

2024-10-07 20:58 UTC, Damonamajor commented on etl/renv.lock
> +      "Source": "GitHub",
I didn't mean to do this, but it seems like we do want the updated Dyfan Jones?

2024-10-09 18:12 UTC, wrridgeway commented on etl/scripts-ccao-data-warehouse-us-east-1/spatial/spatial-environment-traffic.R
> +    # Convert the S3 object into raw data and read using geoarrow
This code seems to be duplicated, now?

2024-10-09 18:13 UTC, Damonamajor commented on etl/scripts-ccao-data-warehouse-us-east-1/spatial/spatial-environment-traffic.R
> +    # Convert the S3 object into raw data and read using geoarrow
yup

2024-10-10 15:52 UTC, wrridgeway commented
@Damonamajor don't forget to update dbt documentation with the new table

2024-10-10 15:54 UTC, Damonamajor commented
> @Damonamajor don't forget to update dbt documentation with the new table

I had it in the next branch, but happy to migrate it over.

2024-10-10 16:38 UTC, wrridgeway commented
yeah, let's just for the spatial.tax table.

couple other things for the warehouse script specifically:
- let's recode `0000` in condition year to `NA`
- let's recode stuff like `surface_type` with the values their numbers correspond to, ie `concrete` rather than `800` for surface type.

2024-11-04 00:34 UTC, wrridgeway requested changes
We're gonna want to make sure `year` is the final column in the upload. I think we're just about there. Wrap up these changes and I'll confirm the data looks correct.

2024-11-04 00:34 UTC, wrridgeway commented on dbt/models/spatial/docs.md
> +Illinois Department of Transportation data source from
Could we do a few words about what's in the data?

2024-11-04 00:34 UTC, wrridgeway commented on etl/scripts-ccao-data-warehouse-us-east-1/spatial/spatial-environment-traffic.R
> +    repeat {
This seems like it would make more sense as a `while` loop.

2024-11-04 00:34 UTC, wrridgeway commented on etl/scripts-ccao-data-warehouse-us-east-1/spatial/spatial-environment-traffic.R
> +      ) %>%
This code feels pretty strange to me. Do we think something like
```
intersecting_pairs <- map(seq_along(intersection_matrix), \(x) {
        data.frame(
          polygon_1 = x,
          polygon_2 = intersection_matrix[[x]]
        )
      }) %>%
        bind_rows() %>%
```
could work?

2024-11-04 15:00 UTC, Damonamajor commented on etl/scripts-ccao-data-warehouse-us-east-1/spatial/spatial-environment-traffic.R
> +  "525" = paste(
lintr was yelling at me.

2024-11-13 15:03 UTC, wrridgeway approved these changes
Great work!

2024-11-13 15:29 UTC, merged